name: Release
run-name: Run by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      # 対象のサブディレクトリ
      directory:
        type: string
        description: 'Target directory. ex: cd <directory> && npm version patch'
  workflow_dispatch:
    inputs:
      # 対象のサブディレクトリ
      directory:
        type: string
        description: 'Target directory. ex: cd <directory> && npm version patch'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release applications
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      packages: write
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      # id-token: write # to enable use of OIDC for npm provenance

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.directory }}/.node_version

      - name: Show Node Version
        run: node --version

      - name: Install Dependencies
        working-directory: ${{ inputs.directory }}
        run: npm ci

      - name: Run Semantic Release
        working-directory: ${{ inputs.directory }}
        run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PACKAGES_NPM_INSTALL_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
