name: Release

on:
  workflow_call:
    inputs:
      # 対象のサブディレクトリ
      directory:
        type: string
        description: 'Target directory. ex: cd <directory> && npm version patch'
  workflow_dispatch:
    inputs:
      # 対象のサブディレクトリ
      directory:
        type: string
        description: 'Target directory. ex: cd <directory> && npm version patch'

jobs:
  release:
    name: Release applications
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      contents: write

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.directory }}/.node_version

      - name: Show Node Version
        run: node --version

      - name: Install Dependencies
        working-directory: ${{ inputs.directory }}
        run: npm ci

      - name: Run Semantic Release
        working-directory: ${{ inputs.directory }}
        run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TPOKEN: ${{ secrets.GITHUB_TOKEN }}
