name: Slack Notification
on:
  workflow_call:
jobs:
  run:
    name: Send a Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Start the Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload: |
            {
              "message": "test",
              "workflow_url": "${{ github.event.workflow_run.url }}",
              "commit": "${{ github.sha }}"
            }
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
