name: GitHub Actions Template        # Workflow name
run-name: Run by @${{ github.actor }} # Workflow run name

# https://docs.github.com/ja/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  workflow_dispatch:                 # Manual event
    inputs:                          # Input parameters  
      env:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
  push:                              # Push event
    branches:
      - main
  pull_request:                      # PR event
    branches:
      - main
# ワークフローレベルで環境変数を定義
env:
  EXAMPLE: example
  REPO_VAR: ${{ vars.REPO_VAR}}
  REPO_SECRET: ${{ secrets.REPO_SECRET }}
# デフォルトシェル
# 未設定の場合： bash -e {0}
# 設定の場合： bash --noprofile --norc -eo pipefail {0}
defaults:
  run:
    shell: bash
# 並行実行の設定. 特にon:pull_reuqestの場合は必須
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  # Workflowレベルで環境変数を使用する方法
  env-with-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${EXAMPLE}"
      - run: echo "${REPO_VAR}"
      - run: echo "${REPO_SECRET}"
  
  # ジョブレベルで環境変数を使用する方法
  env-with-job:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "${BRANCH}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
        
  # ステップ間で環境変数を共有する方法
  env-between-steps:                 # Job name
    runs-on: ubuntu-latest           # Runner type
    steps:                           # Job steps
      - name: input-env
        id: input-env
        run: echo "result=Test" >> "${GITHUB_OUTPUT}"   # Set output variable with Key=Value format
      - name: output-env
        env:
          RESULT: ${{ steps.input-env.outputs.result }}
        run: echo "${RESULT}"
  # ステップ間で環境変数を共有する方法(非推奨)
  env-between-steps-not-recommended:
    runs-on: ubuntu-latest
    steps:
      - name: input-env
        id: input-env
        run: echo "RESULT=Test" >> "${GITHUB_ENV}"   # Set output variable with Key=Value format
      - name: output-env
        run: echo "${RESULT}"
  comment-to-pr:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      contents: read        # ソースコードの読み込みを許可
      pull-requests: write  # PRへの書き込みを許可
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment ${{ github.event.pull_request.number }} --body "Hello, World!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
